### ISSUE TITLE
Inline max-height should be recalculated on view port resize

### ISSUE THREAD

**Issue by chrisyaxley** [stuartjnelson/badger-accordion#19]
Hi,
Really love the Badger Accordion. Only issue I have is when I resize my window the size of my content gets longer as it gets narrower, thus pushing some content below the max-height of the container.
Hope that makes sense?
Thanks for all the work you have put into this,
Chris

**Comment by seanjhulse** [comment]
The line that controls this is here: [here](https://github.com/stuartjnelson/badger-accordion/blob/fbd2b4580616cca923e0d6a0d8057077c2144a3b/src/js/badger-accordion.js#L468)

For now, I _think_ this will temporarily fix your issue if you need this functionality:

```
.badger-accordion--initalised .badger-accordion__panel {
    max-height: none !important;
}
```

But the height is calculated on expansion of the tab. So, you don't need to worry about it not fitting because it's calculated on device height. Eg. Just reload the page and try to open the tab again. It'll now fit.

**Comment by stuartjnelson** [comment]
Hi @chrisyaxley,

Thanks for getting in touch. Thanks @seanjhulse for responding super fast!

Currently, I don't plan to add a resize observer to the plugin. Using the plugins API you could use the Resize Observer API (I'd recommend polyfilling it) and on resize use `calculateAllPanelsHeight()` or `calculatePanelHeight()` depending on your need. You could just fire it on the open panel. 

Here is a [helpful article on the Resize Observer API](https://alligator.io/js/resize-observer/). Any questions feel free to comment on this ticket. I'll leave it open for now.

**Comment by stuartjnelson** [comment]
Hi @chrisyaxley,

I made a little Codesandbox using the Resize Observer API  - [link](https://codesandbox.io/s/l9wzpvjzyl) - this doesn't use the polyfill for the API but I hope helps in getting it working for you. I'll close the ticket now. Any problems feel free to get in touch.
