### ISSUE TITLE
Multiple instances of accordion on same page

### ISSUE THREAD

**Issue by marcobiedermann** [stuartjnelson/badger-accordion#7]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

Create multiple instances on the same page.

# Current Behavior

What is the current behavior?

Currently you can only have one instance per page or you have to give each accordion an unique ID / selector.

## Steps to Reproduce

Create multiple accordions in your HTML wich work independently of each other.

```js
const elements = {
  accordions: document.querySelectorAll('.js-badger-accordion'),
};

Array.from(elements.accordions).forEach((accordion) => {
  const badgerAccordion = new BadgerAccordion(accordion);
});
```

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: macOS
* Browser/s & version/s: Chrome 65
* NPM version: 5.6
* Node version: 9.10

## Solution

Instead of passing a CSS selector as element to the new instance, I suggest passing a DOM node to it:
https://github.com/stuartjnelson/badger-accordion/blob/master/src/js/badger-accordion.js#L19

Currently I give each accordion an unique id to work around this issue but this cost more DOM lookups than nessessary

```js
const elements = {
  accordions: document.querySelectorAll('.js-badger-accordion'),
};

Array.from(elements.accordions).forEach((accordion) => {
  const badgerAccordion = new BadgerAccordion(`#${accordion.id}`);
});
```

**Comment by michaelpumo** [comment]
Wow. Cannot believe you can't have multiple accordions. What an oversight.

**Comment by stuartjnelson** [comment]
Hi @marcobiedermann,

Thanks for reporting this and for your solution! I'll look to get this sorted over the next couple of weeks when I get some spare time. I'll let you know when I've updated the plugin.

**Comment by stuartjnelson** [comment]
Hi @michaelpumo,

If you'd like to report an issue please fill out a new issue ticket using the issue template.

**Comment by getdave** [comment]
I'd like to input here.

I feel it is legit to have each instance be responsible for one dom node hierarchy only. 

That said the accordion needs to allow multiple instances to use the same selector.

To maintain backwards compat i would advise that el is allowed to be either a string OR a dom node. If it is a string then behave "as is" but with a clear note in the docs that you as a user are responsible for managing uniqueness of the selector within the page. This should be marked as a deprecated feature as it isnt the best option.

If the el arg is a DOM node then proceed by assigning container to refer to el. This is because there is no need for an additional use of query selector as it is already a DOM node.

This solution will fix the above problem without breaking backwards compat.

Anyone disagree?

Also, Stu has given up his time to build this tool. A little respect wouldnt go amiss from some of the contributors in this issue. Let's be nice and polite people!

Cheers

**Comment by stuartjnelson** [comment]
Thanks for your help @getdave & @marcobiedermann. I've just done a new release and you can now pass in a DOM node as well as CSS selector.
